# Local environment (default)
spring:
  config:
    activate:
      on-profile: local

  datasource:
    use-in-memory: true
  jpa:
    database: h2
    show-sql: false
    generate-ddl: false
    hibernate:
      generate-statistics: false
      # when we use flyway we should turn of hibernate `ddl-auto`
      ddl-auto: none

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    use-outbox: true
    enabled: true
    
logging:
  level:
    org: info
    com: info

message-persistence:
  interval: 3
  message-persist-provider-type: inmemory
