server:
  port: 9000 # Port for the service
spring:
  application:
    name: api-gateway
  security:
    oauth2:
      # configure the Spring Cloud Gateway and `oauth2-resource-server` package to validate JWT tokens and enforce scopes suing keycloak public keys in the `openid-connect/certs` endpoint
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/food-delivery-microservices
          jwk-set-uri: http://localhost:8080/realms/food-delivery-microservices/protocol/openid-connect/certs
  cloud:
    gateway:
      routes:
        - id: catalogs
          uri: http://localhost:5000
          # uri: lb://catalogs-service # Use lb:// for load balancing
          predicates:
            - Path=/api/{version}/catalogs/**
          filters:
            - RewritePath=/api/(?<version>.*)/catalogs/(?<remainder>.*), /api/$\{version}/$\{remainder}
            # forwards the validated token to the downstream microservices.
            - TokenRelay
            - CorrelationId
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - PreserveHostHeader
          metadata:
            response-timeout: 20000
            connect-timeout: 20000

        - id: users
          uri: http://localhost:7000
          # uri: lb://users-service # Use lb:// for load balancing
          predicates:
            - Path=/api/{version}/users/**
          filters:
            - RewritePath=/api/(?<version>.*)/users/(?<remainder>.*), /api/$\{version}/$\{remainder}
            - TokenRelay
            - CorrelationId
            - PreserveHostHeader
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          metadata:
            response-timeout: 20000
            connect-timeout: 20000

        - id: customers
          uri: http://localhost:8000
          # uri: lb://customers-service # Use lb:// for load balancing
          predicates:
            - Path=/api/{version}/customers/**
          filters:
            - RewritePath=/api/(?<version>.*)/customers/(?<remainder>.*), /api/$\{version}/$\{remainder}
            - TokenRelay
            - CorrelationId
            - PreserveHostHeader
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          metadata:
            response-timeout: 20000
            connect-timeout: 20000

#    # Consul Configuration
#    consul:
#      host: localhost # Consul server host
#      port: 8500 # Consul server port
#      discovery:
#        health-check-path: /actuator/health # Health check endpoint
#        health-check-interval: 10s # Health check interval
#        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# Actuator Configuration (for health checks)
management:
  endpoints:
    web:
      exposure:
        include: health, info # Expose health and info endpoints
  endpoint:
    health:
      show-details: always # Show detailed health information
logging:
  level:
    org: info
    com: info
