# Test environment
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 3
      maximum-pool-size: 5
      pool-name: TestHikariPool
  jpa:
    database: h2
    show-sql: true
    hibernate:
      # when we use flyway we should turn of hibernate `ddl-auto`
      ddl-auto: none
  h2:
    console:
      enabled: true