# https://docs.spring.io/spring-boot/how-to/properties-and-configuration.html
# https://docs.spring.io/spring-boot/reference/features/external-config.html
# Common configurations across all environments

server:
  port: 6000 # Port for the service
spring:
  profiles:
    group:
      local: "dev-tools,dev-db,dev-config,default, local"
      development: "dev-tools,dev-db,dev-config"
      test: "test-db,test-config"
      production: "prod-db,prod-config"
    active: local  # Set the default active profile
    default: local # Set the default profile if none specified

  main:
    banner-mode: off
    web-application-type: servlet
    allow-bean-definition-overriding: true
    log-startup-info: true

  datasource:
    use-in-memory: true
  jpa:
    database: h2
    show-sql: false
    generate-ddl: false
    hibernate:
      # Disable Hibernate's automatic schema updates, when we use flyway we should turn of hibernate `ddl-auto`
      ddl-auto: none
      generate-statistics: false

  data:
    mongodb:
      connection-pool:
        max-size: 100
        min-size: 10
      socket:
        connect-timeout: 5000
        read-timeout: 5000
      host: localhost
      port: 27017
      database: identity
      username: admin
      password: admin
      authentication-database: admin

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    use-outbox: true

  flyway:
    enabled: true
    # migration scripts path
    locations: classpath:db/migration
    baseline-on-migrate: true # Create baseline for existing databases

app:
  version: "1.0.0"
  name: "Identity Service"
  seed:
    enabled: false

swagger:
  title: "Identity Service"
  description: "Identity Service"
  contact-name: "test"
  contact-email: "test@test.com"
  enabled: true
  version: 3
  ui-path: /swagger
  openapi-path: /v3/openapi

problem-details:
  enabled: true
  include-stack-trace: true

otel:
  sdk:
    disabled: false
  resource:
    attributes:
      deployment.environment: dev
      service:
        name: identity
        namespace: identity
  instrumentation-name: "identity-service"
  service-name: "identity-service"
  metrics-enabled: true
  tracing-enabled: true
  logging-enabled: true
  use-prometheus-exporter: true
  prometheus-port: 9464
  use-otlp-grpc-exporter: true
  use-otlp-http-exporter: false
  use-aspire-otlp-exporter: true
  use-console-exporter: false
  use-jaeger-exporter: false
  use-zipkin-exporter: false
  jaeger-options:
    otlp-grpc-endpoint: "http://localhost:14317"
    http-endpoint: "http://localhost:14268/api/traces"
  zipkin-options:
    http-endpoint: "http://localhost:9411/api/v2/spans"
  otlp-options:
    otlp-grpc-endpoint: "http://localhost:4317"
    otlp-http-endpoint: "http://localhost:4318"
  aspire-dashboard-otlp-options:
    otlp-grpc-endpoint: "http://localhost:4319"

mediator:
  enabled: true

validation:
  enabled: true

logging:
  level:
    org: info
    com: info

message-persistence:
  interval: 3
  message-persist-provider-type: inmemory

