### implicit-flow-client
GET {{keycloakAddress}}/realms/food-delivery-microservices/protocol/openid-connect/auth?
  client_id=implicit-flow-client&redirect_uri=http://localhost:3000&response_type=token&
  scope=basic%20email%20profile%20roles&
  state={{STATE}}

> {%
  client.global.set("token", response.body.access_token);
%}

### catalogs-microservice-client
POST {{keycloakAddress}}/realms/food-delivery-microservices/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id = catalogs-microservice-client &
client_secret = {{CATALOGS_MICROSERVICE_CLIENT_SECRET}} &
grant_type = client_credentials &
scope = catalogs-users-service-scope

> {%
  client.global.set("token", response.body.access_token);
%}

### Get Product by ID
GET {{catalogsAddress}}/api/v1/products/{{productId}}
Accept: application/json
Authorization: Bearer {{token}}

### Update Product Details
PUT {{catalogsAddress}}/api/v1/products/{{productId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Updated Product Name",
  "priceAmount": 99.99,
  "currency": "USD",
  "width": 10.5,
  "height": 5.5,
  "depth": 2.5,
  "size": "Medium",
  "sizeUnit": "cm",
  "description": "Updated product description"
}

### Delete Product
DELETE {{catalogsAddress}}/api/v1/products/{{productId}}
Authorization: Bearer {{token}}

### Get Category by ID
GET {{catalogsAddress}}/api/v1/categories/{{categoryId}}
Accept: application/json

### Update Category Details
PUT {{catalogsAddress}}/api/v1/categories/{{categoryId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Updated Category Name",
  "code": "UPDATED_CODE",
  "description": "Updated category description"
}

### Delete Category
DELETE {{catalogsAddress}}/api/v1/categories/{{categoryId}}
Authorization: Bearer {{token}}

### Get Products by Page
GET {{catalogsAddress}}/api/v1/products?pageNumber=0&pageSize=10
Accept: application/json
Authorization: Bearer {{token}}

### Create Product
POST {{catalogsAddress}}/api/v1/products
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "categoryId": "{{categoryId}}",
  "name": "New Product",
  "status": "Active",
  "priceAmount": 49.99,
  "currency": "USD",
  "width": 10.0,
  "height": 5.0,
  "depth": 2.0,
  "size": "Small",
  "sizeUnit": "cm",
  "productVariants": [
    {
      "sku": "SKU123",
      "amount": 49.99,
      "currency": "USD",
      "stock": 100,
      "color": "Red",
      "attributes": {
        "material": "Plastic"
      }
    }
  ],
  "description": "New product description"
}

### Get Categories by Page
GET {{catalogsAddress}}/api/v1/categories?pageNumber=0&pageSize=10
Accept: application/json

### Create Category
POST {{catalogsAddress}}/api/v1/categories
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "New Category",
  "code": "NEW_CAT",
  "description": "New category description"
}

### Search Products by Name
GET {{catalogsAddress}}/api/v1/products/search-by-name?searchTerm=Product&pageNumber=0&pageSize=10
Accept: application/json
Authorization: Bearer {{token}}
