# https://github.com/devcontainers/images/tree/main/src/java
# https://github.com/devcontainers/templates/tree/main/src/java
# https://github.com/devcontainers/images/blob/main/src/java/.devcontainer/devcontainer.json

FROM mcr.microsoft.com/devcontainers/java:latest