# https://docs.spring.io/spring-boot/how-to/properties-and-configuration.html
# https://docs.spring.io/spring-boot/reference/features/external-config.html
# Common configurations across all environments

# export SPRING_PROFILES_ACTIVE=development
# java -jar app.jar --spring.profiles.active=development
# -Dspring.profiles.active=development

server:
  port: 5000

app:
  version: "1.0.0"
  name: "Spring Food Delivery Microservices"
  seed:
    enabled: false

swagger:
  title: "Spring Food Delivery Microservices"
  description: "Spring Food Delivery Microservices"
  contact-name: "test"
  contact-email: "test@test.com"
  enabled: true
  version: 3
  ui-path: /swagger
  openapi-path: /v3/openapi

problem-details:
  enabled: true
  include-stack-trace: true

otel:
  sdk:
    disabled: false
  resource:
    attributes:
      deployment.environment: dev
      service:
        name: catalogs
        namespace: catalogs
  instrumentation-name: "spring-food-delivery-microservices"
  service-name: "spring-food-delivery-microservices"
  metrics-enabled: true
  tracing-enabled: true
  logging-enabled: true
  use-prometheus-exporter: true
  prometheus-port: 9464
  use-otlp-grpc-exporter: true
  use-otlp-http-exporter: false
  use-aspire-otlp-exporter: true
  use-grafana-exporter: false
  use-console-exporter: false
  use-jaeger-exporter: false
  use-zipkin-exporter: false
  jaeger-options:
    otlp-grpc-endpoint: "http://localhost:14317"
    http-endpoint: "http://localhost:14268/api/traces"
  zipkin-options:
    http-endpoint: "http://localhost:9411/api/v2/spans"
  otlp-options:
    otlp-grpc-endpoint: "http://localhost:4317"
    otlp-http-endpoint: "http://localhost:4318"
  aspire-dashboard-otlp-options:
    otlp-grpc-endpoint: "http://localhost:4319"

mediator:
  enabled: true

validation:
  enabled: true

logging:
  level:
    org: info
    com: info

message-persistence:
  interval: 30
  message-persist-provider-type: inmemory

spring:
  main:
    banner-mode: off
    web-application-type: servlet
    allow-bean-definition-overriding: true
    log-startup-info: true

  datasource:
    use-in-memory: true
  jpa:
    database: h2
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  data:
    mongodb:
      connection-pool:
        max-size: 100
        min-size: 10
      socket:
        connect-timeout: 5000
        read-timeout: 5000
      host: localhost
      port: 27017
      database: catalogs
      username: admin
      password: admin
      authentication-database: admin


  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    use-outbox: true


  #  main:
  #    allow-bean-definition-overriding: true
  profiles:
    group:
      local: "dev-tools,dev-db,dev-config,default, local"
      development: "dev-tools,dev-db,dev-config"
      test: "test-db,test-config"
      staging: "stage-db,stage-config"
      production: "prod-db,prod-config"
    active: local  # Set the default active profile
    default: local # Set the default profile if none specified

