# Production environment
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 300000
      connection-timeout: 20000
      pool-name: ProdHikariPool
  jpa:
    database: postgresql
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: false