# https://docs.spring.io/spring-boot/how-to/properties-and-configuration.html
# https://docs.spring.io/spring-boot/reference/features/external-config.html
# Common configurations across all environments

# export SPRING_PROFILES_ACTIVE=development
# java -jar app.jar --spring.profiles.active=development
# -Dspring.profiles.active=development

server:
  port: 5000

app:
  version: "1.0.0"
  name: "vertical slice template"
  seed:
    enabled: false

swagger:
  title: "Vertical Slice Template Api"
  description: "Vertical Slice Template Api"
  contact-name: "test"
  contact-email: "test@test.com"
  enabled: true
  version: 3
  ui-path: /swagger
  openapi-path: /v3/openapi

problem-details:
  enabled: true
  include-stack-trace: true

mediator:
  enabled: true

validation:
  enabled: true

logging:
  level:
    org: info
    com: info

message-persistence:
  interval: 30
  message-persist-provider-type: inmemory

spring:
  main:
    banner-mode: off
    web-application-type: servlet
    allow-bean-definition-overriding: true
    log-startup-info: true

  datasource:
    use-in-memory: true
  jpa:
    database: h2
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  data:
    mongodb:
      connection-pool:
        max-size: 100
        min-size: 10
      socket:
        connect-timeout: 5000
        read-timeout: 5000
      host: localhost
      port: 27017
      database: catalogs
      username: admin
      password: admin
      authentication-database: admin


  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    use-outbox: true


#  #  main:
#  #    allow-bean-definition-overriding: true
#  profiles:
#    group:
#      local: "dev-tools,dev-db,dev-config,default, local"
#      development: "dev-tools,dev-db,dev-config"
#      test: "test-db,test-config"
#      staging: "stage-db,stage-config"
#      production: "prod-db,prod-config"
#    active: local  # Set the default active profile
#    default: local # Set the default profile if none specified
#
