# Development environment

spring:
  config:
    activate:
      on-profile: dev

  # create `catalogs_service` database in `init-postgres.sql` file of postgres container
  datasource:
    url: jdbc:postgresql://localhost:5432/catalogs_service
    username: postgres
    password: postgres
    name: catalogs-connection

  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: false
    hibernate:
      generate-statistics: false
      # when we use flyway we should turn of hibernate `ddl-auto`
      ddl-auto: none

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    use-outbox: true

logging:
  level:
    org: info
    com: info

message-persistence:
  interval: 3
  message-persist-provider-type: postgresql
